# -*- coding: utf-8 -*-
"""tugas3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jRzVfr-lfdl2kGfeUhzo447-r874pxv

**A star search**
"""

from queue import PriorityQueue
from os import path

def reconstruct_path(came_from, start, goal):
    current = goal
    route = [current]
    while current != start:
        current = came_from[current]
        route.append(current)
    route.reverse()
    return route

def greedy_search(graph, start, goal):
    frontier = PriorityQueue()
    frontier.put((heuristic[start], start))
    came_from = {}
    explored = set()

    while not frontier.empty():
        _, current_node = frontier.get()

        if current_node == goal:
            print("Simpul tujuan ditemukan!")
            path = reconstruct_path(came_from, start, goal)
            print("Jalur terpendek:", path)
            return path

        explored.add(current_node)

        for neighbor in graph[current_node]:
            if neighbor not in explored:
                frontier.put((heuristic[neighbor], neighbor))
                came_from[neighbor] = current_node

    print("Simpul tujuan tidak ditemukan!")
    return None

def a_star_search(graph, start, goal, heuristic):
    frontier = PriorityQueue()
    frontier.put((0, start))
    came_from = {}
    cost_so_far = {start: 0}

    while not frontier.empty():
        _, current_node = frontier.get()

        if current_node == goal:
            print("Goal node found!")
            path = reconstruct_path(came_from, start, goal)
            print("Optimal path:", path)
            return path

        for neighbor, cost in graph[current_node].items():
            new_cost = cost_so_far[current_node] + cost
            if neighbor not in cost_so_far or new_cost < cost_so_far[neighbor]:
                cost_so_far[neighbor] = new_cost
                priority = new_cost + heuristic[neighbor]
                frontier.put((priority, neighbor))
                came_from[neighbor] = current_node

    print("Goal node not found!")
    return None

heuristic = {
    'A': 9,
    'B': 4,
    'C': 2,
    'D': 5,
    'E': 7,
    'S': 7,
    'G': 0
}

graph = {
    'S': {'A': 3, 'B': 2},
    'A': {'B': 1, 'D': 5},
    'B': {'D': 3, 'C': 2},
    'C': {'G': 4, 'D': 3},
    'D': {'G': 5}
}

start_node = 'S'
goal_node = 'G'

print("Greedy Best-First Search:")
greedy_search(graph, start_node, goal_node)

print("\nA* (A Star) Search:")
a_star_search(graph, start_node, goal_node, heuristic)